version: "3.8"

services:
  ai-service:
    build: ./chatbot-agent
    container_name: commercial-contents-agent-ai-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

  app-service:
    build: ./app-service
    container_name: commercial-contents-agent-app-service
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
    restart: always
    depends_on:
      - ai-service

  ui:
    build: ./ui
    container_name: commercial-contents-agent-ui
    ports:
      - "3000:3000"