version: "3.8"

services:
  app-service:
    build: ./app-service
    container_name: commercial-contents-agent-app-service
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
    restart: always
  ui:
    build: ./ui
    container_name: commercial-contents-agent-ui
    ports:
      - "3000:3000"