azure_openai_api_key="G1hmHSyJWSer9BPRMmWYUTSNE4uuvY80bzpak9Yf1LzwHDXVxFhgJQQJ99BBACfhMk5XJ3w3AAABACOGOPyy"
azure_openai_endpoint="https://hackathon-thecrewo6.openai.azure.com"
azure_openai_deployment="gpt-4o"
azure_openai_embedding_deployment_name=" text-embedding-3-large"
azure_openai_api_version="2023-06-01-preview"
